/**
 * @file constants
 */

export const FETCH_KEY = "KEYACTIVEPAGE/FETCH_KEY";
export const FETCH_KEY_SUCCESS = "KEYACTIVEPAGE/FETCH_KEY_SUCCESS";

export const GENERATE_KEY = "KEYACTIVEPAGE/GENERATE_KEY";
export const GENERATE_KEY_SUCCESS = "KEYACTIVEPAGE/GENERATE_KEY_SUCCESS";
export const GENERATE_KEY_FAIL = "KEYACTIVEPAGE/GENERATE_KEY_FAIL";


export const HANDLE_INPUT_KEYACTIVE_CHANGE = "KEYACTIVEPAGE/HANDLE_INPUT_KEYACTIVE_CHANGE";
