/**
 * @file constants
 */
export const FETCH_DATA_DASHBOARD = "HOMEPAGE/FETCH_DATA_DASHBOARD";
export const FETCH_DATA_DASHBOARD_SUCCESS = "HOMEPAGE/FETCH_DATA_DASHBOARD_SUCCESS";

export const HANDLE_INPUT_DATLENH_CHANGE = "HOMEPAGE/HANDLE_INPUT_DATLENH_CHANGE";
export const HANDLE_CHANGE_LOAI_DATLENH = "HOMEPAGE/HANDLE_CHANGE_LOAI_DATLENH";
export const HANDLE_VALIDATE = "HOMEPAGE/HANDLE_VALIDATE";

export const UPDATE_STOCKS = "HOMEPAGE/UPDATE_STOCKS";

export const TRADING_CREATE = "HOMEPAGE/TRADING_CREATE";
export const TRADING_CREATE_SUCCESS = "HOMEPAGE/TRADING_CREATE_SUCCESS";
export const TRADING_CREATE_FAIL = "HOMEPAGE/TRADING_CREATE_FAIL";

export const CLEAR_WAITING = "HOMEPAGE/CLEAR_WAITING";
export const UPDATE_TRADING = "HOMEPAGE/UPDATE_TRADING";

export const UPDATE_USER_INFO = "HOMEPAGE/UPDATE_USER_INFO"