/**
 * @file constants
 */

export const REGISTER = "REGISTERPAGE/REGISTER";
export const REGISTER_SUCCESS = "REGISTERPAGE/REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTERPAGE/REGISTER_FAIL";

export const HANDLE_INPUT_CHANGE = "REGISTERPAGE/HANDLE_INPUT_CHANGE";

export const CLEAR = "REGISTERPAGE/CLEAR";
